spring:
  application:
    name: flowable-springboot-demo
  datasource:
    url: jdbc:h2:file:~/flowable-springboot-demo-h2-db}
    username: sa
    password: sa
    #type: org.h2.jdbcx.JdbcDataSource
  h2:
    console:
      enabled: true
      path: /h2-console